# frozen_string_literal: true

# name: discourse-embedding-cluster
# about: A plugin to display a D3 scatterplot with embedding data generated by a Python script.
# version: 1.0.0
# authors: ScottMastro
#url: https://github.com/ScottMastro/discourse-embedding-cluster
# required_version: 2.7.0
# transpile_js: true

enabled_site_setting :embedding_cluster_enabled

register_asset 'stylesheets/common/common.scss'
register_asset 'stylesheets/mobile/mobile.scss', :mobile


after_initialize do
    module ::EmbeddingCluster
      PLUGIN_NAME = "discourse-embedding-cluster"
    end
  
    class EmbeddingCluster::Engine < Rails::Engine
      engine_name EmbeddingCluster::PLUGIN_NAME
      isolate_namespace EmbeddingCluster
    end

  require_relative 'app/controllers/embedding_cluster_controller.rb'
  
  EmbeddingCluster::Engine.routes.draw do
    get '/explore' => 'embedding_cluster#index'
    get '/explore/data' => 'embedding_cluster#data'
  end

  Discourse::Application.routes.append do
    mount ::EmbeddingCluster::Engine, at: "/"
  end
end
#  if SiteSetting.embedding_cluster_enabled
#    Jobs.enqueue_in(
#      SiteSetting.embedding_cluster_update_frequency.days,
#      :update_embedding_cluster_data
#    )
#  end

#  # Handle plugin enabled/disabled state
#  DiscourseEvent.on(:site_setting_saved) do |site_setting|
#    if site_setting.name == 'embedding_cluster_enabled'
#      if SiteSetting.embedding_cluster_enabled
#        Jobs.enqueue(:update_embedding_cluster_data)
#      else
#        Jobs.cancel_scheduled_job(:update_embedding_cluster_data)
#      end
#    end
#  end
#end